[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/sheynor43/SLAM"
publish = false

[workspace.dependencies]
libc = "0.2.190"
rtrb = "0.4.0"
sdl3-sys = { version = "0.7.2", default-features = false }
thiserror = "2.0.21"
windows-sys = { version = "0.61.2", features = ["Win32_Foundation", "Win32_Security", "Win32_System_Performance", "Win32_System_Threading"] }

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "deny"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
