[package]
name = "slam-render"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
glow.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
slam-testkit = { path = "../slam-testkit" }

[build-dependencies]
slam-shader-build = { path = "../slam-shader-build" }

[lints]
workspace = true
