[package]
name = "slam-engine"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
slam-input = { path = "../slam-input" }
slam-render = { path = "../slam-render" }
slam-audio = { path = "../slam-audio" }
thiserror.workspace = true

[lints]
workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
libc.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys.workspace = true

[dev-dependencies]
glow.workspace = true
tracing-subscriber.workspace = true
slam-testkit = { path = "../slam-testkit" }
